package com.jackandphantom.demon;
public class Constants {
    public static String SERVER_IP = "10.5.50.170";
    public static String PLAY = "play";
    public static String NEXT = "192.168.0.1/0/102";
    public static String PREVIOUS = "192.168.0.1/0/102";
    public static String MOUSE_LEFT_CLICK = "left_click";
    public static int port = 3000;
    static String VOLUME_UP = "volume_up";
    static String VOLUME_DOWN = "volume_down";
    static String Q = "q";
    static String W = "w";
    static String E = "e";
    static String R = "r";
    static String T = "t";
    static String Y = "y";
    static String U = "u";
    static  String I = "i";
    static  String O = "o";
    static  String P = "p";
    static  String A = "a";
    static  String S = "s";
    static  String D = "d";
    static String F = "f";
    static String G = "g";
    static String H = "h";
    static String J = "j";
    static String K = "k";
    static String L = "l";
    static  String Z = "z";
    static  String X = "x";
    static  String C = "c";
    static String V = "v";
    static String B = "b";
    static  String N = "n";
    static  String ALT = "alt";
    static  String SHIFT = "shift";
    static String UP = "up";
    static String DOWN = "down";
    static String ENTER = "enter";
}

